import React from 'react'
import Head from 'next/head'
import CourseCard from '@/components/reusables/CourseCard'

function index() {
  const courses=[
    {
      id:0,
      courseTitle:'JavaScript',
      link:'js',
      img:'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png'
    },
    {
      id:1,
      courseTitle:'Python',
      link:'py',
      img:'https://images.ctfassets.net/mrop88jh71hl/55rrbZfwMaURHZKAUc5oOW/9e5fe805eb03135b82e962e92169ce6d/python-programming-language.png'
    },
    {
      id:2,
      courseTitle:'Java',
      link:'java',
      img:'https://www.developer.com/wp-content/uploads/2021/09/Java-tutorials.jpg'
    },
  ]
  return (
    <>
      <Head>
            <title>Codebasics | Courses</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
              {/* Header */}
            <div className='w-full h-[40vh] relative'>
                <div className='absolute top-0 left-0 bg-[rgba(0,0,0,0.7)] w-full h-full'>
                </div>
                <img src={`https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y29kZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=2000&q=60`}
                width={500} height={500} 
                className='w-full h-full object-cover' alt='about'/>
                <div className='absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]
                 text-white text-center w-full p-5'>
                    <p className='uppercase tracking-widest text-3xl'>Courses</p>
                    <p className='text-xl'>Scan Through our List of courses, and select the one you're interested in!</p>
                </div>
                
            </div>
            <section className='max-w-[1600px] mx-auto h-full'>
               <section className='grid grid-cols-1 lg:grid-cols-2 p-5 gap-5'>
                {
                  courses.map((item)=>{
                    return(
                      <CourseCard key={item.id} title={item.courseTitle} link={item.link} img={item.img}/>
                    )
                  })
                }
               </section>
            </section>
      </main>
    </>
  )
}

export default index